name: 'Jest Coverage Reporter Action'
description: 'Provide a coverage report based on a base/master coverage report'
branding:
  icon: git-pull-request
  color: orange
inputs:
  base-coverage-report-path:
    required: false
    description: 'Path to base coverage report (not required if AWS credentials are provided)'
  branch-coverage-report-path:
    required: false
    description: 'Path to the current coverage report (not required if AWS credentials are provided)'
  accessToken:
    description: 'access token required to comment on a pr'
    default: ${{ github.token }}
  fullCoverageDiff:
    description: 'get the full coverage with diff or only the diff'
    default: false
  delta:
    description: 'Difference between the old and final test coverage'
    default: 0.2
  useSameComment:
    description: 'While commenting on the PR update the exisiting comment'
    default: true
  custom-message:
    description: 'Pass any custom string which will be displayed in the comment'
    default: ''
  only-check-changed-files:
    description: 'Only test for changed files in the PR'
    default: true
  prefix-filename-url:
    description: 'Add a base URL to the filenames and make it a hyperlink'
    default: ''
  check-new-file-full-coverage:
    description: 'Check newly added files whether have full coverage tests'
    default: true
  new-file-coverage-threshold:
    description: 'Threshold for new file coverage'
    default: 100
  coverageType:
    required: false
    description: 'Tools that generate code coverage'
    default: 'jest'
  aws-access-key-id:
    required: false
    description: 'AWS access key ID for S3 operations'
  aws-secret-access-key:
    required: false
    description: 'AWS secret access key for S3 operations'
  aws-region:
    required: false
    description: 'AWS region for S3 operations'
    default: 'us-east-2'
  s3-bucket:
    required: false
    description: 'S3 bucket name for storing coverage reports'
  s3-repo-directory:
    required: false
    description: 'Directory inside the S3 bucket dedicated to this repository'
    default: ''
  base-branch:
    required: false
    description: 'Base branch name (e.g., main or master)'
    default: 'main'
  pr-number:
    required: false
    description: 'Pull request number'
  s3-base-url:
    required: false
    description: 'Base URL for S3 coverage reports'

runs:
  using: 'node20'
  main: 'dest/index.js'
