name: 'Jest Coverage Reporter Action'
description: 'Provide a coverage report based on a base/master coverage report'
branding:
  icon: git-pull-request
  color: orange
inputs:
  base-coverage-report-path:
    required: true
    description: 'Path to base coverage report'
  branch-coverage-report-path:
    required: true
    description: 'Path to the current coverage report'
  accessToken:
    description: 'access token required to comment on a pr'
    default: ${{ github.token }}
  fullCoverageDiff:
    description: 'get the full coverage with diff or only the diff'
    default: false
  delta:
    description: 'Difference between the old and final test coverage'
    default: 0.2
  useSameComment:
    description: 'While commenting on the PR update the exisiting comment'
    default: true
  custom-message:
    description: 'Pass any custom string which will be displayed in the comment'
    default: ''
  only-check-changed-files:
    description: 'Only test for changed files in the PR'
    default: true
  prefix-filename-url:
    description: 'Add a base URL to the filenames and make it a hyperlink'
    default: ''
  check-new-file-full-coverage:
    description: 'Check newly added files whether have full coverage tests'
    default: true
  coverageType:
    required: false
    description: 'Tools that generate code coverage'
    default: 'jest'

runs:
  using: 'node20'
  main: 'dest/index.js'
