name: 'Jest Coverage Reporter Action'
description: 'Provide a coverage report based on a base/master coverage report'
branding:
  icon: git-pull-request
  color: orange
inputs:
  base-coverage-report-path:
    required: true
    description: 'Path to base coverage report'
  branch-coverage-report-path:
    required: true
    description: 'Path to the current coverage report'
  accessToken:
    description: 'access token required to comment on a pr'
    default: ${{ github.token }}
  fullCoverageDiff:
    description: 'get the full coverage with diff or only the diff'
    default: false
  delta:
    description: 'Difference between the old and new total test coverage'
    default: 0.03
  useSameComment:
    description: 'While commenting on the PR update the exisiting comment'
    default: true
  custom-message:
    description: 'Pass any custom string which will be displayed in the comment'
    default: ''
  check-total-coverage-only:
    description: 'Only check total coverage and not coverage on individual files'
    default: false

runs:
  using: 'node12'
  main: 'dest/index.js'
