name: CI

env:
  NODE_VERSION: 14.17.3
  MASTER_SHA: ''

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - uses: actions/checkout@v2

      - name: jest coverage reporter
        uses: ./ # Uses an action in the root directory
        id: coverage-reporter
        with:
          branch-coverage-report-path: ./coverage/coverage-summary.json
          base-coverage-report-path: ./coverage/coverage-summary-master.json
          useSameComment: true

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: install yarn
        run: npm install -g yarn
      
      - name: yarn install, build, and test
        run: |
          yarn install  --frozen-lockfile

      - name: Danger
        run: yarn danger ci
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
