name: CI

env:
  NODE_VERSION: 20.11.1
  MASTER_SHA: ''

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - uses: actions/checkout@v4

      - name: jest coverage reporter
        uses: ./ # Uses an action in the root directory
        id: coverage-reporter
        with:
          branch-coverage-report-path: ./coverage/coverage-summary.json
          base-coverage-report-path: ./coverage/coverage-summary-master.json
          useSameComment: true
          coverageType: jest
          fullCoverageDiff: true
          new-file-coverage-threshold: 90
          only-check-changed-files: false

      - name: cobertura coverage reporter
        uses: ./ # Uses an action in the root directory
        id: cobertura-coverage-reporter
        with:
          branch-coverage-report-path: ./coverage/cobertura.xml
          base-coverage-report-path: ./coverage/cobertura-master.xml
          useSameComment: true
          coverageType: cobertura
          only-check-changed-files: false
          check-new-file-full-coverage: false
          prefix-filename-url: 'https://tubi-web-assets-staging.s3.us-east-2.amazonaws.com/larnaca-coverage-artifacts'
