name: CI

env:
  NODE_VERSION: 14.17.3
  MASTER_SHA: ''

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - uses: actions/checkout@v2

      - name: jest coverage reporter
        uses: ./ # Uses an action in the root directory
        id: coverage-reporter
        with:
          branch-coverage-report-path: ./coverage/coverage-summary.json
          base-coverage-report-path: ./coverage/coverage-summary-master.json
          useSameComment: true   

      - name: cobertura coverage reporter
        uses: ./ # Uses an action in the root directory
        id: cobertura-coverage-reporter
        with:
          branch-coverage-report-path: ./coverage/cobertura.xml
          base-coverage-report-path: ./coverage/cobertura-master.xml
          useSameComment: true          